HOSTS:
  el7:
    roles:
      - default
      - server
    platform: el-7-x86_64
    box: centos/7
    hypervisor: vagrant
    vagrant_memsize: 2048
    vagrant_cpus: 3
    yum_repos:
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch'
        gpgkeys:
          - https://getfedora.org/static/352C64E5.txt

CONFIG:
  log_level: verbose
  type: foss
